-- Pastor Rhema PLUS — Tabelas de infraestrutura Hotmart
-- Execute este arquivo todo no SQL Editor do Supabase

-- ============================================
-- 1. HOTMART USER EMAILS (lookup O(1) email → user_id)
-- ============================================
create table if not exists public.hotmart_user_emails (
  email text not null primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone default now()
);

create index if not exists idx_hotmart_user_emails_user_id
  on public.hotmart_user_emails(user_id);

alter table public.hotmart_user_emails enable row level security;

-- Apenas service_role pode ler/escrever (usado pelo webhook e admin)
create policy "Service role full access on hotmart_user_emails"
  on public.hotmart_user_emails
  for all
  using (true)
  with check (true);

-- ============================================
-- 2. WEBHOOK LOGS (observabilidade)
-- ============================================
create table if not exists public.webhook_logs (
  id bigint generated by default as identity primary key,
  event text,
  email text,
  plan text,
  action text not null check (action in ('created', 'updated', 'skipped', 'error')),
  reason text,
  payload_event text,
  incoming_plan text,
  applied boolean,
  error_message text,
  duration_ms integer,
  created_at timestamp with time zone default now()
);

create index if not exists idx_webhook_logs_event on public.webhook_logs(event);
create index if not exists idx_webhook_logs_email on public.webhook_logs(email);
create index if not exists idx_webhook_logs_created_at on public.webhook_logs(created_at desc);
create index if not exists idx_webhook_logs_action on public.webhook_logs(action);

alter table public.webhook_logs enable row level security;

-- Service role — insert e read
create policy "Service role full access on webhook_logs"
  on public.webhook_logs
  for all
  using (true)
  with check (true);

-- Admins autenticados podem ler via API admin
create policy "Authenticated users can read webhook_logs"
  on public.webhook_logs
  for select
  using (auth.role() = 'authenticated');
