export const T = {
  bg: "#f4f7fb",
  surface: "#ffffff",
  surface2: "#f8fafc",
  surface3: "#eef4ff",
  text: "#0f172a",
  muted: "#64748b",
  line: "#e2e8f0",
  primary: "#0b2a5b",
  primary2: "#163d7a",
  gold: "#caa14a",
  green: "#16a34a",
  greenDark: "#15803d",
  greenSoft: "#dcfce7",
  blueSoft: "#dbeafe",
  amberSoft: "#fef3c7",
  violetSoft: "#ede9fe",
  redSoft: "#fee2e2",
  radius: "22px",
  radiusSm: "14px",
  shadow: "0 14px 40px rgba(15,23,42,0.08)",
  shadowLg: "0 24px 70px rgba(11,42,91,0.16)",
  font: "'Libre Baskerville', 'Georgia', serif",
  fontSans: "'DM Sans', 'Segoe UI', system-ui, sans-serif",
};

export const inputStyle = {
  width: "100%",
  border: `1px solid ${T.line}`,
  background: T.surface2,
  borderRadius: T.radiusSm,
  padding: "14px 15px",
  color: T.text,
  outline: "none",
  fontFamily: T.fontSans,
  fontSize: "14px",
  boxSizing: "border-box",
};
